# Generated by Django 5.2.3 on 2025-07-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_position_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Unnamed', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
